### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by wioux** [EFForg/sec#183]

**Comment by lschatzkin** [comment]
Contact, 
secfeedback@eff.org 

Privacy - link to eff privacy page

Credits - to come

**Comment by lschatzkin** [comment]
Name in all caps:

![ssd-logo-400](https://user-images.githubusercontent.com/852512/32682556-427b773c-c62a-11e7-847f-242b97c699ab.png)
![eff-logo-300](https://user-images.githubusercontent.com/852512/32682557-4711c1e8-c62a-11e7-9d6e-fcb198070150.png)
