### ISSUE TITLE
Topics/lessons

### ISSUE THREAD

**Issue by vbrown608** [EFForg/sec#2]

**Comment by vbrown608** [comment]
Starting on the user-facing side of this.

**Comment by vbrown608** [comment]
Still needs 
- js show/hide if we're keeping that
- TOC if we're adding it
- put a class on the active tab

plus some other small updates to match the mockup

**Comment by wioux** [comment]
Direct linking to a particular lesson difficulty is broken

**Comment by wioux** [comment]
Tabs / tags layout don't survive on mobile

**Comment by wioux** [comment]
Add last updated to admin edit actions

**Comment by wioux** [comment]
* Make sure paste from google docs preserves formatting
* + ADD on a new topic doesn't work
* Lesson objective field should be ckeditor
* Teacher/learner ratios should be more free form
* Prerequisites should be free form
* Materials should allow things like "a projector", etc.

* max-height on lesson body is too short, content gets cut off

**Comment by wioux** [comment]
Still problems with wickedhtmltopdf

**Comment by wioux** [comment]
Add a field for extra content that can appear before the cutoff

**Comment by vbrown608** [comment]
Renaming:
required materials -> suggested materials
students will -> learners will

create a style that can be used within the wysiwyg that will look the same as section headers like "learning materials"
