### ISSUE TITLE
header style difference should be more visible

### ISSUE THREAD

**Issue by lenazun** [EFForg/sec#206]
the headers (particularly between h2, h3) should have more of a visible difference

**Comment by lschatzkin** [comment]
h1 {
  font-size: 1.6rem;
  line-height: 2rem;
  margin-bottom: 1rem;
  @include breakpoint(medium) {
    font-size: 2rem;
    line-height: 2.3rem;
    margin-bottom: 1.6rem;
  }
}

h2 {
  font-size: 1.7rem;
  line-height: 1.9rem;
  margin-bottom: 1.3rem;
  margin-top: 3rem;
  @include breakpoint(medium) {
    font-size: 1.5rem;
    line-height: 1.7rem;
    margin-bottom: 1.6rem;
  }
}


h3 {
  font-size: 1.2rem;
  line-height: 1.8rem;
  margin-bottom: 0.7rem;
}

h4 {
  font-size: 1rem;
  line-height: 1.4rem;
  margin-bottom: 0.5rem;
  text-align: left;
}
