### ISSUE TITLE
social media icons on side of lesson modules and sec 101

### ISSUE THREAD

**Issue by lenazun** [EFForg/sec#209]
it would be nice to have social media / share icons on the side of the lesson modules & Sec Ed 101 pieces

**Comment by meeseachelle** [comment]
We'd the share links to behave the same way as they do on the main site: https://www.eff.org/deeplinks/2017/11/announcing-security-education-companion
sticky to the left edge with the text slide out on hover
![google](https://user-images.githubusercontent.com/13072303/33103139-68da37d4-ced5-11e7-8b6e-3ecda577c2db.png)
![facebook](https://user-images.githubusercontent.com/13072303/33103140-68f6316e-ced5-11e7-9c7f-adab12ef61aa.png)
![twitter](https://user-images.githubusercontent.com/13072303/33103141-6924d7b2-ced5-11e7-8eb1-fc723bc804e3.png)
