### ISSUE TITLE
Fallback images for materials uploads we can't autogenerate previews for

### ISSUE THREAD

**Issue by vbrown608** [EFForg/sec#223]
When users upload files to materials, we generate a thumbnail preview for images and pdfs. For other filetypes, we'd like to have a fallback images. The buckets are:

* "documents" like .docx, .doc, and .odp
* .pptx, which may not be used exactly like a slide deck - Soraya can say more about its use
* a generic fallback for anything else we might encounter

**Comment by hughillustration** [comment]
How about something like these: 
![doc](https://user-images.githubusercontent.com/10857936/32757896-9ed1de40-c896-11e7-967c-e7f03399ba2a.png)
![docx](https://user-images.githubusercontent.com/10857936/32757897-9eef608c-c896-11e7-9441-be86a79ddbda.png)
![odp](https://user-images.githubusercontent.com/10857936/32757898-9f086c3a-c896-11e7-9030-7c05c01b6a1e.png)
![pdf](https://user-images.githubusercontent.com/10857936/32757899-9f1d93b2-c896-11e7-964d-e551056f065c.png)
![pptx](https://user-images.githubusercontent.com/10857936/32757900-9f39c5e6-c896-11e7-8862-aa6a3e6555f9.png)

**Comment by vbrown608** [comment]
Looks good to me, I'm going to swap them in. ping @eff-soraya for sign-off.

**Comment by hughillustration** [comment]
Ah — should it say “document” or something?

H.

**Comment by vbrown608** [comment]
I think I will see if there's a way for us to just use real text on a background color for these instead of an image - then we can just display the file extension. I'll update shortly.

**Comment by vbrown608** [comment]
I think that using actual text should work. What font + weight is this?

**Comment by hughillustration** [comment]
Montserrat 600 all caps.

H.
