### ISSUE TITLE
Picking backup typefaces? Tor Browser renders Montserrat in a very strange way.

### ISSUE THREAD

**Issue by eff-soraya** [EFForg/sec#239]
I previewed the site in Tor Browser, and it seems to have issues with recognizing the typeface. This also affects the "back to SSD" button.

![screen shot 2017-11-08 at 5 51 36 pm](https://user-images.githubusercontent.com/16709499/32584555-b8a5f53c-c4ad-11e7-9d7c-ab18fbb05eda.png)
![screen shot 2017-11-08 at 5 52 15 pm](https://user-images.githubusercontent.com/16709499/32584557-bb79941c-c4ad-11e7-8002-723d3bfcb5ce.png)

I've included SSD for contrast, as the backup font for SSD seems to be quite nice. 

![screen shot 2017-11-08 at 5 56 30 pm](https://user-images.githubusercontent.com/16709499/32584636-42f895be-c4ae-11e7-9196-574da05d5477.png)

**Comment by hughillustration** [comment]
It should fall back to sans serif/arial for Tor browsers or if the font can’t load.

H.
