### ISSUE TITLE
Mobile specific - Security Education 101 - Curated content links need some styling

### ISSUE THREAD

**Issue by eff-soraya** [EFForg/sec#243]
A lot is happening visually: 
Some styling tweaks would be appreciated for this section, since the suggested reading takes up a lot of the screen, and the H1 is competing for attention.
![img_5044](https://user-images.githubusercontent.com/16709499/32585207-2ab8b6b6-c4b1-11e7-9cc5-300ac3326d13.png)

**Comment by wioux** [comment]
Put table of contents beneath introduction text.
