### ISSUE TITLE
Yarn security issues

### ISSUE THREAD

**Issue by ghost** [EFForg/sec#245]
[Yarn uses SHA-1](https://github.com/yarnpkg/yarn/issues/816) and [unzips downloaded files before checking their hashes](https://github.com/yarnpkg/yarn/issues/4638). I don't think EFF should use Yarn. They should use NPM instead.

**Comment by mfb** [comment]
I think npm would also use only SHA-1? unless we upgrade the build environment to use current version of npm

**Comment by koops76** [comment]
@mfb At least NPM checks the file hashes before unzipping them.

**Comment by koops76** [comment]
@mfb NPM only uses SHA-1 for old packages, new packages use SHA-256.
