### ISSUE TITLE
Front page / Teaching materials - Width + Height standardization

### ISSUE THREAD

**Issue by eff-soraya** [EFForg/sec#250]
The Teaching Materials preview graphics stretch out the box in a way that's visually not-so-great.

I'd like for them to fit neatly in three columns, with a standard height and weight for the containing boxes.

Screenshot from the materials section, for context:
![screen shot 2017-11-09 at 1 08 56 pm](https://user-images.githubusercontent.com/16709499/32629783-36998d7c-c54f-11e7-9c8a-93a110d84164.png)

Screenshot from the front page, for context:
![screen shot 2017-11-09 at 1 08 47 pm](https://user-images.githubusercontent.com/16709499/32629787-39f50096-c54f-11e7-8138-be8e534a2a2a.png)

**Comment by vbrown608** [comment]
@hughillustration do you have a mockup for these pages?

**Comment by hughillustration** [comment]
Hi, yes — I’d like the materials section to look like this on the front page:



The preview images about 126px high. The boxes stack on mobile.

H.

**Comment by hughillustration** [comment]
Here’s how I think the Materials page should work. Pretty simple change:

* preview has 1px box
* move download link to directly below the preview
* increase padding between preview and next item

H.

**Comment by lschatzkin** [comment]
![sec-materials-mock-1](https://user-images.githubusercontent.com/852512/32681995-21330e08-c627-11e7-8054-380e66345d7b.png)

**Comment by lschatzkin** [comment]
![sec-materials-2](https://user-images.githubusercontent.com/852512/32682015-31ac060e-c627-11e7-8dc1-fc75628a8739.png)
