### ISSUE TITLE
Styling for lesson icons

### ISSUE THREAD

**Issue by lschatzkin** [EFForg/sec#263]
example: https://sec.eff.org/topics

**Comment by hughillustration** [comment]
I’d like these to look like this — 3 in a row. Will that work?

I have noun-project graphics coming for each lesson shortly.

H.

**Comment by lschatzkin** [comment]
I'm not seeing what you're referring to, but it sounds like you want a grid of 3 instead of 2. correct?

**Comment by hughillustration** [comment]
Yes — can you see the image?

**Comment by lschatzkin** [comment]
No, for some reason I can't. Want to put it on mattermost?

**Comment by hughillustration** [comment]
Sure.

**Comment by lschatzkin** [comment]
![lessons-1](https://user-images.githubusercontent.com/852512/32681944-e6b2784a-c626-11e7-8f45-d7bd6e57e7b7.jpg)
