### ISSUE TITLE
For small(/medium?) screens, stack lesson 3-column area

### ISSUE THREAD

**Issue by wioux** [EFForg/sec#296]
The `.meta` area for lessons gets pretty squished as screen size decreases.

**Comment by lschatzkin** [comment]
Is this for the home page?

**Comment by wioux** [comment]
No, on topic pages like https://sec.eff.org/topics/passwords

The ratio/suggested materials/suggested reading columns should maybe be stacked for mobile:

![sec-mobile-3col](https://user-images.githubusercontent.com/6469642/32867513-506dcb1e-ca22-11e7-82c0-ebbfa595857a.png)

**Comment by lschatzkin** [comment]
Okay, got it!
