### ISSUE TITLE
Materials content doesn't fit within squares

### ISSUE THREAD

**Issue by vbrown608** [EFForg/sec#306]
Looks like the materials content isn't fitting with the square cards on the overview page. They might be more consistently sized after cropping ( #301 ) but it will still be hard to make squares that contain all of the content for every card without awkward amounts of whitespace on others. I'm wondering if we could relax the requirement that they be square.

**Comment by lschatzkin** [comment]
This has been fixed, they are not square on widths that would cause an overflow problem.
