### ISSUE TITLE
Printable pages generated: including SEC icon + name at the top + sec.eff.org, plus "A project of the Electronic Frontier Foundation"

### ISSUE THREAD

**Issue by eff-soraya** [EFForg/sec#333]
Hugh and I would like to include the logo, name, sec.eff.org, and "a project of the Electronic Frontier Foundation" at the top of generated printed PDFs.
Thanks!

**Comment by hughillustration** [comment]
If this image can be set as the header, that will work great.
[PDF-header.pdf](https://github.com/EFForg/sec/files/1476401/PDF-header.pdf)

**Comment by lenazun** [comment]
![pdf-header](https://user-images.githubusercontent.com/6117168/32864065-8fbb7452-ca12-11e7-94bf-03176bf66104.png)
