### ISSUE TITLE
Creating a style for captions in images.

### ISSUE THREAD

**Issue by eff-soraya** [EFForg/sec#393]
I noticed that captions come across as body text. I was wondering if we can reduce the size for captions on images significantly, so that they don't stick out as much? Moving to roughly 8 pt would be good. 

See example below, where the upper text is p text, and the bottom text is the caption format.
![screen shot 2018-01-18 at 11 06 30 am](https://user-images.githubusercontent.com/16709499/35116329-ebf43d8a-fc3f-11e7-8850-16a7ca0bdc9a.png)

**Comment by hughillustration** [comment]
+1

H.
