### ISSUE TITLE
Fix permissions for lesson plan sharing

### ISSUE THREAD

**Issue by vbrown608** [EFForg/sec#428]
Users who did not create the lesson plan can still remove lessons.

**Comment by wioux** [comment]
Looking closer at this I think it's just a UI issue and will be fixed with #427. `LessonPlansController` finds plans for update based on a session variable, and finds them for display based on the URL param, so shared lesson plans shouldn't be updateable on the back end.

**Comment by vbrown608** [comment]
I'm going to add back and clean up the sharing widget as part of this

**Comment by vbrown608** [comment]
I'm wondering whether users should see edit buttons (like X and reorder) when they visit their lesson plan at its full path.

They may not notice/differentiate between the two paths and therefore get confused if they visit the permalink and lose edit buttons.

On the other hand, I think the downside would be that users might not know/understand whether others will see the edit buttons as well.

Maybe a good compromise would be to should a special notice when a user visits their own lesson plan at its full path.
