### ISSUE TITLE
Remove 'back to SSD' from every page except for homepage

### ISSUE THREAD

**Issue by meeseachelle** [EFForg/sec#432]
Currently on homepage <img width="1006" alt="screen shot 2018-03-27 at 2 42 09 pm" src="https://user-images.githubusercontent.com/13072303/37996611-1f9bddec-31cd-11e8-848b-161d696e0fe7.png">

Would like to remove the arrow on the homepage
![back to ssd](https://user-images.githubusercontent.com/13072303/37996749-8f94c514-31cd-11e8-9cd3-f427c79705d5.png)

and the remaining pages would look like this: 
![header ssd](https://user-images.githubusercontent.com/13072303/37997033-8ff84188-31ce-11e8-8c5e-2f2530c1ad70.png)

**Comment by wioux** [comment]
I'm going to close this since it is related to #429 and fixed by the branch addressing that issue.
