### ISSUE TITLE
Rename lesson_plan_lesson

### ISSUE THREAD

**Issue by vbrown608** [EFForg/sec#455]
I'm working on reordering and there's so much `lesson_plan_lesson.lesson`. 

I was thinking it might be nice to rename `lesson_plan_lesson` to `planned_lesson` and delegate some stuff to its' lesson, like name, topic, duration, difficulty. Then we could do planned_lesson.position, planned_lesson.name, etc.

What do you think?

**Comment by wioux** [comment]
+1 lesson_plan_lesson.lesson is tedious every time, and delegating all the basic attributes seems very useful.

**Comment by vbrown608** [comment]
This will be a good opportunity to improve my vim find-and-replace tools...
