### ISSUE TITLE
Lesson plan counter cache doesn't update after call to update_attributes

### ISSUE THREAD

**Issue by vbrown608** [EFForg/sec#457]
After removing a lesson_plan_lesson like `@lesson_plan.update_attributes(lesson_plan_params)`, `@lesson_plan.lessons` is empty, but `@lesson_plan.lessons_count` is still 1. Calling `@lesson_plan.reload` brings them back in sync, but I don't think that should be necessary.

**Comment by wioux** [comment]
I customized the counter column to avoid another use of lesson_plan_lessons, so its name is "lessons_count" while the update callbacks are probably looking for "lesson_plan_lessons_count". We could add `counter_cache: "lessons_count"` to the has_many options for that association, or when we rename the association also rename the column to planned_lessons_count.
