### ISSUE TITLE
Accessibility - color contrast for lesson level labels

### ISSUE THREAD

**Issue by okaysoraya** [EFForg/sec#514]
Picking slightly different color pairings for the lesson level labels: The contrast for Beginner/Intermediate labels on the preview of the Modules are too dark in contrast, e.g. black against green and black against mustard yellow apparently don’t meet contrast standards.
![screen shot 2018-08-03 at 1 16 18 pm](https://user-images.githubusercontent.com/16709499/43663737-6fc63792-971f-11e8-83ee-1128fee589b3.png)

**Comment by lschatzkin** [comment]
@okaysoraya Did we already change these? They are passing WAVE on my browser.

**Comment by lschatzkin** [comment]
confirming these are passing WAVE, closing issue.
