### ISSUE TITLE
Usability - Admin interface - issue with hover in the corner

### ISSUE THREAD

**Issue by okaysoraya** [EFForg/sec#544]
In the admin interface, the right-corner user icon has a menu that expands by default upon hover. It has a wide area for the hover section, however, making it hard to see or interact with links that are placed under this icon. This conflicts with spaces like page: TOPICS > link: NEW TOPIC. 

Any chance we can change this menu from a hover-based interaction that expands out, to requiring an affirmative click on the user icon? I'm open to other solutions as well—the main thing I"m concerned about is not being able to click on the NEW TOPIC link within the admin interface :)

**Comment by vbrown608** [comment]
Yes this is so annoying :upside_down_face:
