### ISSUE TITLE
as soon as able? - Download / PDF generator not working

### ISSUE THREAD

**Issue by okaysoraya** [EFForg/sec#564]
![Screen Shot 2019-09-12 at 1 24 07 PM](https://user-images.githubusercontent.com/16709499/64818510-10afa000-d561-11e9-8d55-6ae8075a964d.png)
I'm attempting to get our content to translators through the PDF and zip file export, but neither is working. Tested using desktop Google Chrome and Firefox -- any chance there's a bug here?

**Comment by wioux** [comment]
Sorry for the delay on this! It should be working now. @okaysoraya

**Comment by okaysoraya** [comment]
Incredible! Thank you Peter :)

> On Jan 10, 2020, at 4:15 PM, Peter Woo <notifications@github.com> wrote:
> 
> Sorry for the delay on this! It should be working now. @okaysoraya
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 


—
Soraya Okuda
she/her || they/them

Want to teach digital security? Check out EFF's Security Education Companion at 
https://sec.eff.org/ and Surveillance Self-Defense at https://ssd.eff.org.

┳┻| 
┻┳| 
┻┳|•.•)   <3 support eff
┳┻| ⊂ﾉ     eff.org/donate
┻┳|
