### ISSUE TITLE
Logout dropdown menu obscuring new content button in admin interface

### ISSUE THREAD

**Issue by krcarlson** [EFForg/sec#566]
Anytime the cursor gets even slightly close to the user icon in the top right corner, the logout dropdown menu appears and will not minimize. This covers up whatever "new content" link is under the dropdown (dependent on where you are in the admin interface). The only way to click the button/link under the dropdown menu is to make your window very small (basically a mobile view) and then the link is far enough below the user icon that the menu does not appear.

Let's remove hover-based interactions from the interface if it's possible.

**Comment by wtcruft** [comment]
I wasn't observing this behavior on SEC, talked to @wioux about it and he found this commit https://github.com/EFForg/sec/commit/48d335cd9ff54cdda449a7f63361ec5d08aaf56a with the fix :) Closing!
